### ISSUE TITLE
Width of Pins on Mux Breakout Board.

### ISSUE THREAD

**Issue by DkCheyne** [sparkfun/Analog_Digital_MUX_Breakout#2]
Currently the distance horizontally between the two headers is marked as .6 inches on the board file when in the current production model it is .5 inches physically.

**Comment by nseidle** [comment]
I checked our board file and stock on the shelf. The distance between header pins is 0.6". 

![image](https://user-images.githubusercontent.com/117102/38957129-f0d20184-4316-11e8-99db-e1d0626a177a.png)

I'm closing this issue because everything checks out from our side. Can you post a picture of your board? I'm curious what is going on.
